// Phase 2 — PDF Generation Utility
// Uses jsPDF + jspdf-autotable to generate real downloadable PDFs

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const BRAND_COLOR: [number, number, number] = [0, 123, 255];    // #007BFF
const DARK_COLOR: [number, number, number] = [26, 37, 48];      // #1A2530
const MUTED_COLOR: [number, number, number] = [100, 116, 139];  // slate-500

function addClinicHeader(doc: jsPDF, clinicName: string, subtitle: string, docName: string, date: string) {
    // Blue accent bar
    doc.setFillColor(...BRAND_COLOR);
    doc.rect(0, 0, 210, 28, 'F');

    // Clinic name
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(clinicName, 14, 14);

    // Subtitle
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle, 14, 22);

    // Doctor + Date right-aligned
    doc.text(`${docName}  |  ${date}`, 196, 14, { align: 'right' });

    // Reset text color
    doc.setTextColor(...DARK_COLOR);
}

function addFooter(doc: jsPDF) {
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(7);
        doc.setTextColor(...MUTED_COLOR);
        doc.text(
            `Generated by Dentora • ${new Date().toLocaleString('en-IN')}  |  Page ${i} of ${pageCount}`,
            14,
            doc.internal.pageSize.height - 8
        );
        // Bottom accent line
        doc.setDrawColor(...BRAND_COLOR);
        doc.setLineWidth(0.5);
        doc.line(14, doc.internal.pageSize.height - 12, 196, doc.internal.pageSize.height - 12);
    }
}

export interface PrescriptionData {
    patientName: string;
    patientPhone?: string;
    patientAllergies?: string;
    doctorName: string;
    clinicName: string;
    date: string;
    drugs: { name: string; dosage: string; frequency: string; duration: string }[];
    notes?: string;
    rxId?: string;
}

export function downloadPrescriptionPDF(data: PrescriptionData): void {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    addClinicHeader(
        doc,
        data.clinicName || 'DentiSphere Clinic',
        data.doctorName + ' · BDS, MDS',
        'Prescription',
        new Date(data.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    );

    // Rx Symbol
    doc.setFontSize(36);
    doc.setFont('times', 'italic');
    doc.setTextColor(...BRAND_COLOR);
    doc.text('℞', 180, 42);

    // Patient info box
    doc.setFillColor(240, 247, 255);
    doc.roundedRect(14, 34, 155, 18, 3, 3, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...DARK_COLOR);
    doc.text('Patient:', 18, 43);
    doc.setFont('helvetica', 'normal');
    doc.text(data.patientName, 38, 43);
    if (data.patientPhone) {
        doc.setFont('helvetica', 'bold');
        doc.text('Phone:', 18, 49);
        doc.setFont('helvetica', 'normal');
        doc.text(data.patientPhone, 38, 49);
    }
    if (data.patientAllergies) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(220, 50, 50);
        doc.text(`Allergies: ${data.patientAllergies}`, 100, 43);
        doc.setTextColor(...DARK_COLOR);
    }

    // Drug table
    autoTable(doc, {
        startY: 58,
        head: [['#', 'Drug Name', 'Dosage', 'Frequency', 'Duration']],
        body: data.drugs.map((d, i) => [
            (i + 1).toString(),
            d.name,
            d.dosage,
            d.frequency,
            d.duration,
        ]),
        headStyles: {
            fillColor: BRAND_COLOR,
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            fontSize: 9,
        },
        bodyStyles: { fontSize: 9, textColor: DARK_COLOR },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 65 } },
        margin: { left: 14, right: 14 },
    });

    let y = (doc as any).lastAutoTable.finalY + 8;

    // Notes
    if (data.notes) {
        doc.setFillColor(254, 252, 232);
        doc.roundedRect(14, y, 182, 16, 3, 3, 'F');
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(146, 64, 14);
        doc.text('Special Instructions:', 18, y + 7);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK_COLOR);
        doc.text(data.notes, 18, y + 13);
        y += 22;
    }

    // Signature block
    y = Math.max(y, 230);
    doc.setDrawColor(...DARK_COLOR);
    doc.setLineWidth(0.3);
    doc.line(130, y + 20, 196, y + 20);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(data.doctorName, 163, y + 25, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...MUTED_COLOR);
    doc.text('Signature & Stamp', 163, y + 30, { align: 'center' });

    addFooter(doc);
    doc.save(`Rx_${data.patientName.replace(/\s+/g, '_')}_${data.date}.pdf`);
}

export interface InvoiceData {
    invoiceNumber: string;
    date: string;
    patientName: string;
    patientPhone?: string;
    patientAddress?: string;
    clinicName: string;
    clinicLocation: string;
    doctorName: string;
    treatmentName: string;
    grossAmount: number;
    discount: number;
    gstRate: number;
    gstAmount: number;
    totalAmount: number;
    paymentMethod: string;
    paymentStatus: string;
}

export function downloadInvoicePDF(data: InvoiceData): void {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    addClinicHeader(
        doc,
        data.clinicName || 'DentiSphere Clinic',
        data.clinicLocation + '  |  ' + data.doctorName,
        'Tax Invoice',
        new Date(data.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    );

    // "INVOICE" watermark
    doc.setFontSize(48);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 123, 255);
    doc.setGState(new (doc as any).GState({ opacity: 0.05 }));
    doc.text('INVOICE', 105, 145, { align: 'center', angle: 45 });
    doc.setGState(new (doc as any).GState({ opacity: 1 }));

    // Invoice number badge
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND_COLOR);
    doc.text(`# ${data.invoiceNumber}`, 196, 38, { align: 'right' });
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED_COLOR);
    doc.text(new Date(data.date).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }), 196, 44, { align: 'right' });

    // Bill-to block
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, 34, 90, 26, 3, 3, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...MUTED_COLOR);
    doc.text('BILL TO', 18, 41);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK_COLOR);
    doc.text(data.patientName, 18, 48);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    if (data.patientPhone) doc.text(data.patientPhone, 18, 54);
    if (data.patientAddress) doc.text(data.patientAddress, 18, 58);

    // Payment block
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(110, 34, 86, 26, 3, 3, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...MUTED_COLOR);
    doc.text('PAYMENT', 114, 41);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK_COLOR);
    doc.text(data.paymentMethod, 114, 48);
    // Status badge
    const statusColors: Record<string, [number, number, number]> = {
        paid: [5, 150, 105], unpaid: [220, 50, 50], partial: [217, 119, 6]
    };
    const statusBg: Record<string, [number, number, number]> = {
        paid: [209, 250, 229], unpaid: [254, 226, 226], partial: [254, 243, 199]
    };
    const sKey = data.paymentStatus.toLowerCase();
    doc.setFillColor(...(statusBg[sKey] || [241, 245, 249]));
    doc.roundedRect(114, 51, 30, 6, 1, 1, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...(statusColors[sKey] || [100, 116, 139]));
    doc.text(data.paymentStatus.toUpperCase(), 129, 55.5, { align: 'center' });

    // Line items table
    autoTable(doc, {
        startY: 68,
        head: [['#', 'Description', 'Amount (₹)']],
        body: [[1, data.treatmentName, `₹${data.grossAmount.toLocaleString('en-IN')}`]],
        headStyles: { fillColor: BRAND_COLOR, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 10, textColor: DARK_COLOR },
        columnStyles: { 0: { cellWidth: 12 }, 2: { halign: 'right' } },
        margin: { left: 14, right: 14 },
    });

    let y = (doc as any).lastAutoTable.finalY + 6;

    // Totals block
    const totals: [string, string][] = [
        ['Gross Amount', `₹${data.grossAmount.toLocaleString('en-IN')}`],
    ];
    if (data.discount > 0) totals.push(['Discount', `− ₹${data.discount.toLocaleString('en-IN')}`]);
    if (data.gstAmount > 0) totals.push([`GST (${data.gstRate}%)`, `₹${data.gstAmount.toLocaleString('en-IN')}`]);

    doc.setDrawColor(226, 232, 240);
    totals.forEach(([label, val]) => {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...MUTED_COLOR);
        doc.text(label, 140, y);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...DARK_COLOR);
        doc.text(val, 196, y, { align: 'right' });
        doc.setLineWidth(0.2);
        doc.line(130, y + 3, 196, y + 3);
        y += 8;
    });

    // Grand total
    doc.setFillColor(...BRAND_COLOR);
    doc.roundedRect(130, y, 66, 12, 2, 2, 'F');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('Net Payable', 134, y + 8);
    doc.text(`₹${data.totalAmount.toLocaleString('en-IN')}`, 192, y + 8, { align: 'right' });

    // Signature
    y += 24;
    y = Math.max(y, 220);
    doc.setDrawColor(...DARK_COLOR);
    doc.setLineWidth(0.3);
    doc.line(130, y + 18, 196, y + 18);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK_COLOR);
    doc.text(data.doctorName, 163, y + 23, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...MUTED_COLOR);
    doc.text('Authorized Signature', 163, y + 28, { align: 'center' });

    addFooter(doc);
    doc.save(`Invoice_${data.invoiceNumber}.pdf`);
}
