// Phase 2 — PDF Generation Utility
// Uses jsPDF + jspdf-autotable to generate real downloadable PDFs

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const BRAND_COLOR: [number, number, number] = [0, 123, 255];    // #007BFF
const DARK_COLOR: [number, number, number] = [26, 37, 48];      // #1A2530
const MUTED_COLOR: [number, number, number] = [100, 116, 139];  // slate-500

function addClinicHeader(doc: jsPDF, clinicName: string, subtitle: string, docName: string, date: string) {
    // Blue accent bar
    doc.setFillColor(...BRAND_COLOR);
    doc.rect(0, 0, 210, 32, 'F');

    // Clinic name
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(clinicName || 'DentiSphere Premium Clinic', 14, 15);

    // Subtitle / Address / Contact header elements
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle || 'Multi-Speciality Dental & Aesthetic Center', 14, 21);
    doc.text('123 Health Street, Clinic District, TN 627003', 14, 25);
    doc.text('Ph: +91 91234 56789 | support@dentora.com', 14, 29);

    // Doctor + Date right-aligned
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(`${docName}  |  ${date}`, 196, 14, { align: 'right' });

    // Reset text color
    doc.setTextColor(...DARK_COLOR);
}

function addFooter(doc: jsPDF) {
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(7);
        doc.setTextColor(...MUTED_COLOR);
        doc.text(
            `Generated by Dentora • ${new Date().toLocaleString('en-IN')}  |  Page ${i} of ${pageCount}`,
            14,
            doc.internal.pageSize.height - 8
        );
        // Bottom accent line
        doc.setDrawColor(...BRAND_COLOR);
        doc.setLineWidth(0.5);
        doc.line(14, doc.internal.pageSize.height - 12, 196, doc.internal.pageSize.height - 12);
    }
}

export interface PrescriptionData {
    patientName: string;
    patientPhone?: string;
    patientAllergies?: string;
    doctorName: string;
    clinicName: string;
    date: string;
    drugs: { name: string; dosage: string; frequency: string; duration: string }[];
    notes?: string;
    rxId?: string;
}

export function downloadPrescriptionPDF(data: PrescriptionData): void {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    addClinicHeader(
        doc,
        data.clinicName || 'DentiSphere Clinic',
        data.doctorName + ' · BDS, MDS',
        'Prescription',
        new Date(data.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    );

    // Rx Symbol
    doc.setFontSize(36);
    doc.setFont('times', 'italic');
    doc.setTextColor(...BRAND_COLOR);
    doc.text('℞', 180, 42);

    // Patient info box
    doc.setFillColor(240, 247, 255);
    doc.roundedRect(14, 34, 155, 18, 3, 3, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...DARK_COLOR);
    doc.text('Patient:', 18, 43);
    doc.setFont('helvetica', 'normal');
    doc.text(data.patientName, 38, 43);
    if (data.patientPhone) {
        doc.setFont('helvetica', 'bold');
        doc.text('Phone:', 18, 49);
        doc.setFont('helvetica', 'normal');
        doc.text(data.patientPhone, 38, 49);
    }
    if (data.patientAllergies) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(220, 50, 50);
        doc.text(`Allergies: ${data.patientAllergies}`, 100, 43);
        doc.setTextColor(...DARK_COLOR);
    }
    // Drug table
    autoTable(doc, {
        startY: 58,
        head: [['#', 'Drug Name', 'Dosage', 'Frequency', 'Duration']],
        body: data.drugs.map((d, i) => [
            (i + 1).toString(),
            d.name,
            d.dosage,
            d.frequency,
            d.duration,
        ]),
        headStyles: {
            fillColor: BRAND_COLOR,
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            fontSize: 9,
        },
        bodyStyles: { fontSize: 9, textColor: DARK_COLOR },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 65 } },
        margin: { left: 14, right: 14 },
    });

    let y = (doc as any).lastAutoTable.finalY + 8;

    // Notes
    if (data.notes) {
        doc.setFillColor(254, 252, 232);
        doc.roundedRect(14, y, 182, 16, 3, 3, 'F');
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(146, 64, 14);
        doc.text('Special Instructions:', 18, y + 7);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK_COLOR);
        doc.text(data.notes, 18, y + 13);
        y += 22;
    }

    // Signature block
    y = Math.max(y, 230);
    doc.setDrawColor(...DARK_COLOR);
    doc.setLineWidth(0.3);
    doc.line(130, y + 20, 196, y + 20);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(data.doctorName, 163, y + 25, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...MUTED_COLOR);
    doc.text('Signature & Stamp', 163, y + 30, { align: 'center' });

    addFooter(doc);
    const filename = `Prescription_${data.patientName.replace(/\s+/g, '_')}_${new Date(data.date).toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
}

export interface TreatmentPlanData {
    patientName: string;
    patientPhone?: string;
    planTitle: string;
    date: string;
    items: { treatment_name: string; tooth_reference: string; cost: number; status: string }[];
    totalCost: number;
    discountAmount?: number;
    notes?: string;
}

export function downloadTreatmentPlanPDF(data: TreatmentPlanData): void {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    addClinicHeader(
        doc,
        'DentiSphere Clinic',
        'Clinical Treatment Roadmap',
        'Treatment Plan',
        new Date(data.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    );

    // Patient info box
    doc.setFillColor(240, 247, 255);
    doc.roundedRect(14, 34, 182, 18, 3, 3, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...DARK_COLOR);
    doc.text('Patient:', 18, 43);
    doc.setFont('helvetica', 'normal');
    doc.text(data.patientName, 38, 43);
    if (data.patientPhone) {
        doc.setFont('helvetica', 'bold');
        doc.text('Phone:', 110, 43);
        doc.setFont('helvetica', 'normal');
        doc.text(data.patientPhone, 130, 43);
    }
    doc.setFont('helvetica', 'bold');
    doc.text('Plan Title:', 18, 49);
    doc.setFont('helvetica', 'normal');
    doc.text(data.planTitle, 38, 49);

    // Items table
    autoTable(doc, {
        startY: 58,
        head: [['#', 'Treatment', 'Teeth', 'Cost (₹)', 'Status']],
        body: data.items.map((it, i) => [
            (i + 1).toString(),
            it.treatment_name,
            it.tooth_reference || '—',
            `₹${it.cost.toLocaleString('en-IN')}`,
            it.status
        ]),
        headStyles: { fillColor: BRAND_COLOR, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 9, textColor: DARK_COLOR },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        margin: { left: 14, right: 14 },
    });

    let y = (doc as any).lastAutoTable.finalY + 10;

    // Totals
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`Total Estimated Cost: ₹${data.totalCost.toLocaleString('en-IN')}`, 196, y, { align: 'right' });
    if (data.discountAmount) {
        y += 6;
        doc.setTextColor(220, 50, 50);
        doc.text(`Discount: − ₹${data.discountAmount.toLocaleString('en-IN')}`, 196, y, { align: 'right' });
        y += 6;
        doc.setTextColor(...BRAND_COLOR);
        doc.text(`Net Amount: ₹${(data.totalCost - data.discountAmount).toLocaleString('en-IN')}`, 196, y, { align: 'right' });
    }

    addFooter(doc);
    const filename = `TreatmentPlan_${data.patientName.replace(/\s+/g, '_')}_${new Date(data.date).toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
}

export interface LabOrderData {
    orderId: string;
    date: string;
    patientName: string;
    patientPhone?: string;
    doctorName: string;
    vendorName: string;
    teeth?: string[];
    prosthesis?: string[];
    preOp?: string[];
    surfaceCluster?: string;
    ponticType?: string;
    shades?: { upper?: string; lower?: string; gingival?: string };
    deliveryNotes?: string;
    status: string;
    deliveryDates: { trial?: string; bisque?: string; final?: string };
}

export function downloadLabOrderPDF(data: LabOrderData, mode: 'download' | 'share' = 'download'): void {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    addClinicHeader(
        doc,
        'DentiSphere Clinic',
        data.doctorName || 'Attending Doctor',
        'Lab Order',
        new Date(data.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    );

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`Order ID: #${(data.orderId || '').slice(0, 8)}`, 14, 40);

    // Info Grid
    const info = [
        ['Patient Name', data.patientName, 'Lab / Vendor', data.vendorName],
        ['Contact', data.patientPhone || 'N/A', 'Status', data.status],
        ['Teeth Selection', data.teeth?.join(', ') || 'N/A', '', '']
    ];

    autoTable(doc, {
        startY: 44,
        body: info,
        theme: 'plain',
        bodyStyles: { fontSize: 9, textColor: DARK_COLOR, cellPadding: 2 },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 30 }, 2: { fontStyle: 'bold', cellWidth: 30 } }
    });

    let y = (doc as any).lastAutoTable.finalY + 10;

    doc.setFont('helvetica', 'bold');
    doc.text('Order Details & Instructions:', 14, y);
    y += 6;

    // Build Specifications detail list
    const specFields = [];
    if (data.shades?.upper) specFields.push(`Upper Shade: ${data.shades.upper}`);
    if (data.shades?.lower) specFields.push(`Lower Shade: ${data.shades.lower}`);
    if (data.shades?.gingival) specFields.push(`Gingival Shade: ${data.shades.gingival}`);
    if (data.surfaceCluster) specFields.push(`Surface: ${data.surfaceCluster}`);
    if (data.ponticType) specFields.push(`Pontic: ${data.ponticType}`);
    if (data.deliveryNotes) specFields.push(`Notes: ${data.deliveryNotes}`);
    const specsText = specFields.join('\n') || '—';

    // Build Schedule List
    const scheduleFields = [];
    if (data.deliveryDates.trial) scheduleFields.push(`Trial Fit: ${data.deliveryDates.trial}`);
    if (data.deliveryDates.bisque) scheduleFields.push(`Bisque Trial: ${data.deliveryDates.bisque}`);
    if (data.deliveryDates.final) scheduleFields.push(`Final Delivery: ${data.deliveryDates.final}`);
    const scheduleText = scheduleFields.join('\n') || 'TBD';

    const itemsList = [...(data.preOp || []), ...(data.prosthesis || [])];
    const tableBody = itemsList.map(item => [
        item,
        specsText,
        scheduleText
    ]);
    if (tableBody.length === 0) {
         tableBody.push(['General Lab Work', specsText, scheduleText]);
    }

    autoTable(doc, {
        startY: y,
        head: [['Item / Task', 'Specifications (Shade, Surface, Pontic)', 'Schedule']],
        body: tableBody,
        theme: 'grid',
        bodyStyles: { fontSize: 8, textColor: DARK_COLOR },
        headStyles: { fillColor: BRAND_COLOR, textColor: [255, 255, 255], fontStyle: 'bold' },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 40 }, 1: { cellWidth: 80 } }
    });

    addFooter(doc);
    const filename = `LabOrder_${data.patientName.replace(/\s+/g, '_')}_${new Date(data.date).toISOString().split('T')[0]}.pdf`;
    
    if (mode === 'share') {
        const blob = doc.output('blob');
        const file = new File([blob], filename, { type: 'application/pdf' });
        
        const msg = `Hello,\n\nPlease find the Lab Order details for patient ${data.patientName} (Order ID: #${data.orderId.slice(0, 8)}).\n\nBest regards,\n${data.doctorName}`;
        
        if (navigator.canShare && navigator.canShare({ files: [file] })) {
            navigator.share({ files: [file], title: 'Lab Order', text: `Lab Order for ${data.patientName}` }).catch(() => {});
        } else {
            window.open(`mailto:?subject=${encodeURIComponent('Lab Order - ' + data.patientName)}&body=${encodeURIComponent(msg)}`);
        }
    } else {
        doc.save(filename);
    }
}

export interface InvoiceData {
    invoiceNumber: string;
    date: string;
    patientName: string;
    patientPhone?: string;
    patientAddress?: string;
    clinicName: string;
    clinicLocation: string;
    doctorName: string;
    treatmentName: string;
    grossAmount: number;
    discount: number;
    gstRate: number;
    gstAmount: number;
    totalAmount: number;
    paymentMethod: string;
    paymentStatus: string;
}

export function downloadInvoicePDF(data: InvoiceData): void {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    addClinicHeader(
        doc,
        data.clinicName || 'DentiSphere Clinic',
        data.clinicLocation + '  |  ' + data.doctorName,
        'Tax Invoice',
        new Date(data.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    );

    // "INVOICE" watermark
    doc.setFontSize(48);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 123, 255);
    doc.setGState(new (doc as any).GState({ opacity: 0.05 }));
    doc.text('INVOICE', 105, 145, { align: 'center', angle: 45 });
    doc.setGState(new (doc as any).GState({ opacity: 1 }));

    // Invoice number badge
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND_COLOR);
    doc.text(`# ${data.invoiceNumber}`, 196, 38, { align: 'right' });
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED_COLOR);
    doc.text(new Date(data.date).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }), 196, 44, { align: 'right' });

    // Bill-to block
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, 34, 90, 26, 3, 3, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...MUTED_COLOR);
    doc.text('BILL TO', 18, 41);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK_COLOR);
    doc.text(data.patientName, 18, 48);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    if (data.patientPhone) doc.text(data.patientPhone, 18, 54);
    if (data.patientAddress) doc.text(data.patientAddress, 18, 58);

    // Payment block
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(110, 34, 86, 26, 3, 3, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...MUTED_COLOR);
    doc.text('PAYMENT', 114, 41);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK_COLOR);
    doc.text(data.paymentMethod, 114, 48);
    // Status badge
    const statusColors: Record<string, [number, number, number]> = {
        paid: [5, 150, 105], unpaid: [220, 50, 50], partial: [217, 119, 6]
    };
    const statusBg: Record<string, [number, number, number]> = {
        paid: [209, 250, 229], unpaid: [254, 226, 226], partial: [254, 243, 199]
    };
    const sKey = data.paymentStatus.toLowerCase();
    doc.setFillColor(...(statusBg[sKey] || [241, 245, 249]));
    doc.roundedRect(114, 51, 30, 6, 1, 1, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...(statusColors[sKey] || [100, 116, 139]));
    doc.text(data.paymentStatus.toUpperCase(), 129, 55.5, { align: 'center' });

    // Line items table
    autoTable(doc, {
        startY: 68,
        head: [['#', 'Description', 'Amount (₹)']],
        body: [[1, data.treatmentName, `₹${data.grossAmount.toLocaleString('en-IN')}`]],
        headStyles: { fillColor: BRAND_COLOR, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 10, textColor: DARK_COLOR },
        columnStyles: { 0: { cellWidth: 12 }, 2: { halign: 'right' } },
        margin: { left: 14, right: 14 },
    });

    let y = (doc as any).lastAutoTable.finalY + 6;

    // Totals block
    const totals: [string, string][] = [
        ['Gross Amount', `₹${data.grossAmount.toLocaleString('en-IN')}`],
    ];
    if (data.discount > 0) totals.push(['Discount', `− ₹${data.discount.toLocaleString('en-IN')}`]);
    if (data.gstAmount > 0) totals.push([`GST (${data.gstRate}%)`, `₹${data.gstAmount.toLocaleString('en-IN')}`]);

    doc.setDrawColor(226, 232, 240);
    totals.forEach(([label, val]) => {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...MUTED_COLOR);
        doc.text(label, 140, y);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...DARK_COLOR);
        doc.text(val, 196, y, { align: 'right' });
        doc.setLineWidth(0.2);
        doc.line(130, y + 3, 196, y + 3);
        y += 8;
    });

    // Grand total
    doc.setFillColor(...BRAND_COLOR);
    doc.roundedRect(130, y, 66, 12, 2, 2, 'F');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('Net Payable', 134, y + 8);
    doc.text(`₹${data.totalAmount.toLocaleString('en-IN')}`, 192, y + 8, { align: 'right' });

    // Signature
    y += 24;
    y = Math.max(y, 220);
    doc.setDrawColor(...DARK_COLOR);
    doc.setLineWidth(0.3);
    doc.line(130, y + 18, 196, y + 18);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK_COLOR);
    doc.text(data.doctorName, 163, y + 23, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...MUTED_COLOR);
    doc.text('Authorized Signature', 163, y + 28, { align: 'center' });

    addFooter(doc);
    const filename = `Invoice_${data.patientName.replace(/\s+/g, '_')}_${data.invoiceNumber}.pdf`;
    doc.save(filename);
}

export interface ConsentData {
    patientName: string;
    patientPhone?: string;
    doctorName: string;
    date: string;
    title: string;
    body: string;
    signatureUrl?: string;
    formId: string;
}

export function downloadConsentPDF(data: ConsentData): void {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    addClinicHeader(
        doc,
        'DentiSphere Clinic',
        'Informed Consent Form',
        'Legal Record',
        new Date(data.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    );

    doc.setFillColor(240, 247, 255);
    doc.roundedRect(14, 34, 182, 18, 3, 3, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...DARK_COLOR);
    doc.text('Patient Name:', 18, 43);
    doc.setFont('helvetica', 'normal');
    doc.text(data.patientName, 45, 43);
    doc.setFont('helvetica', 'bold');
    doc.text('Date:', 18, 49);
    doc.setFont('helvetica', 'normal');
    doc.text(new Date(data.date).toLocaleString(), 45, 49);
    doc.setFont('helvetica', 'bold');
    doc.text('Doctor:', 110, 43);
    doc.setFont('helvetica', 'normal');
    doc.text(data.doctorName, 130, 43);
    doc.setFont('helvetica', 'bold');
    doc.text('Ref ID:', 110, 49);
    doc.setFont('helvetica', 'normal');
    doc.text(`#${data.formId.slice(0, 8)}`, 130, 49);

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND_COLOR);
    doc.text(data.title, 14, 64);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...DARK_COLOR);
    const splitBody = doc.splitTextToSize(data.body, 182);
    doc.text(splitBody, 14, 72);

    let y = 72 + (splitBody.length * 5) + 10;
    y = Math.max(y, 200);
    doc.setDrawColor(...MUTED_COLOR);
    doc.line(14, y + 20, 80, y + 20);
    doc.setFontSize(8);
    doc.text('Patient Signature', 47, y + 25, { align: 'center' });
    
    if (data.signatureUrl) {
        try {
            doc.addImage(data.signatureUrl, 'PNG', 20, y - 5, 40, 20);
        } catch (e) {
            console.error('Signature attachment failed', e);
        }
    }

    doc.line(130, y + 20, 196, y + 20);
    doc.text('Doctor Signature / Audit', 163, y + 25, { align: 'center' });
    doc.setFont('helvetica', 'italic');
    doc.text(data.doctorName, 163, y + 18, { align: 'center' });

    addFooter(doc);
    const filename = `Consent_${data.title.replace(/\s+/g, '_')}_${data.patientName.replace(/\s+/g, '_')}.pdf`;
    doc.save(filename);
}

export interface MedicalClearanceData {
    formId: string;
    date: string;
    patientName: string;
    patientAge: string;
    doctorName: string;
    physicianName: string;
    provisionalDiagnosis: string;
    proposedTreatment: string;
    medicalHistory: string;
    currentMedications: string;
    fitnessStatus: string;
    specialInstructions: string;
    clinicName?: string;
    signatureUrl?: string;
}

export function downloadMedicalClearancePDF(data: MedicalClearanceData): void {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    addClinicHeader(
        doc,
        data.clinicName || 'DentiSphere Clinic',
        'Request for Medical Opinion / Clearance',
        'Medical Evaluation',
        new Date(data.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    );

    let y = 38;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`Ref ID: #${data.formId.slice(0, 8).toUpperCase()}`, 14, y);
    y += 10;

    doc.setFont('helvetica', 'normal');
    doc.text('To,', 14, y); y += 5;
    doc.setFont('helvetica', 'bold');
    doc.text(`The Physician / Specialist`, 14, y); y += 5;
    doc.text(data.physicianName || 'Attending Physician', 14, y); y += 8;

    doc.setFont('helvetica', 'bold');
    doc.text('Subject: Request for medical evaluation and clearance', 14, y); y += 10;

    doc.setFont('helvetica', 'normal');
    doc.text('Dear Doctor,', 14, y); y += 8;

    doc.setFont('helvetica', 'normal');
    doc.text('I would like to refer my patient ', 14, y);
    const w1 = doc.getTextWidth('I would like to refer my patient ');
    
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 38, 38); // RED Color
    const pText = `${data.patientName}, aged ${data.patientAge || '____'}`;
    doc.text(pText, 14 + w1, y);
    const w2 = doc.getTextWidth(pText);
    
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(26, 37, 48); // Reset to Dark Black
    doc.text(', who reported to our clinic with a dental complaint.', 14 + w1 + w2, y);
    y += 10;

    // Section 1: Diagnosis
    doc.setFont('helvetica', 'bold');
    doc.text('Provisional Diagnosis:', 14, y); y += 6;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 38, 38); // RED Color for user type-in
    const splitDiag = doc.splitTextToSize(data.provisionalDiagnosis || 'N/A', 182);
    doc.text(splitDiag, 14, y);
    y += (splitDiag.length * 5) + 6;
    doc.setTextColor(26, 37, 48); // Reset

    // Section 2: Proposed Treatment
    doc.setFont('helvetica', 'bold');
    doc.text('Proposed Dental Treatment:', 14, y); y += 6;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 38, 38); // RED Color for user type-in
    const splitTreat = doc.splitTextToSize(data.proposedTreatment || 'N/A', 182);
    doc.text(splitTreat, 14, y);
    y += (splitTreat.length * 5) + 6;
    doc.setTextColor(26, 37, 48); // Reset

    // Section 3: Medical History
    doc.setFont('helvetica', 'bold');
    doc.text('Medical History:', 14, y); y += 6;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 38, 38); // RED Color for user type-in
    const splitMed = doc.splitTextToSize(data.medicalHistory || 'N/A', 182);
    doc.text(splitMed, 14, y);
    y += (splitMed.length * 5) + 6;
    doc.setTextColor(26, 37, 48); // Reset

    // Section 4: Current Medications
    doc.setFont('helvetica', 'bold');
    doc.text('Current Medications:', 14, y); y += 6;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 38, 38); // RED Color for user type-in
    const splitMedication = doc.splitTextToSize(data.currentMedications || 'N/A', 182);
    doc.text(splitMedication, 14, y);
    y += (splitMedication.length * 5) + 8;
    doc.setTextColor(26, 37, 48); // Reset to Dark for list headers

    doc.setFont('helvetica', 'bold');
    doc.text('In view of the patient’s medical status, I kindly request your expert opinion regarding:', 14, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    const points = [
        '- Fitness of the patient to undergo the planned dental procedure under local anesthesia',
        '- Any modifications required in ongoing medications',
        '- Need for antibiotic prophylaxis, if indicated',
        '- Any specific precautions or contraindications to be considered prior to treatment'
    ];
    points.forEach(point => {
        doc.text(point, 18, y);
        y += 5;
    });
    y += 5;

    doc.text('Kindly provide your valuable opinion and clearance to proceed with the planned dental management.', 14, y);
    y += 10;

    doc.text('Thank you for your cooperation.', 14, y);
    y += 15;

    // Doctor Signature line
    doc.setFont('helvetica', 'bold');
    doc.text('Yours sincerely,', 14, y); y += 5;
    doc.text(`Dr. ${data.doctorName}`, 14, y); y += 4;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text('BDS / MDS', 14, y); y += 4;
    doc.text(data.clinicName || 'Clinic Manager', 14, y);
    y += 15;

    // ── PHYSICIAN FEEDBACK SECTION ──
    doc.setDrawColor(200, 200, 200);
    doc.line(14, y, 196, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 123, 255);
    doc.text('PHYSICIAN EVALUATION & CLEARANCE', 14, y);
    doc.setTextColor(26, 37, 48); // Reset
    y += 8;

    doc.setFontSize(10);
    doc.text(`Fitness Status: `, 14, y);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 38, 38); // RED Color
    doc.text(data.fitnessStatus || 'Pending / Under Evaluation', 42, y);
    doc.setTextColor(26, 37, 48); // Reset to Dark
    y += 8;

    doc.setFont('helvetica', 'bold');
    doc.text('Special Instructions / Recommendations:', 14, y);
    y += 6;
    doc.setFont('helvetica', 'bold'); // Change to Bold!
    doc.setTextColor(220, 38, 38); // RED Color
    const splitInstructions = doc.splitTextToSize(data.specialInstructions || '__________________________________________________________________________________________', 182);
    doc.text(splitInstructions, 14, y);
    doc.setTextColor(26, 37, 48); // Reset back to default Dark for remaining footer elements layout!
    y += (splitInstructions.length * 5) + 15;

    // Signature placeholders
    y = Math.max(y, 230);
    doc.setDrawColor(0, 0, 0);
    doc.line(14, y, 80, y);
    doc.line(130, y, 196, y);
    y += 5;
    doc.setFontSize(8);
    doc.text('Physician Signature & Stamp', 47, y, { align: 'center' });
    doc.text('Date', 163, y, { align: 'center' });

    if (data.signatureUrl) {
        try {
            // Physician might fill/sign it physically, but if uploaded later we support it
            doc.addImage(data.signatureUrl, 'PNG', 20, y - 25, 40, 20);
        } catch (e) { }
    }

    addFooter(doc);
    const filename = `MedicalClearance_${data.patientName.replace(/\s+/g, '_')}.pdf`;
    doc.save(filename);
}

